### ISSUE TITLE
Add clearificaion to README

### ISSUE THREAD

**Issue by ShalokShalom** [snowfallorg/icehouse#2]
The current state of the README, does not unveil, what the software is for.

**Comment by quantenzitrone** [comment]
i quickly looked through the code and i think its for creating and backing up ZFS pools.

**Comment by ShalokShalom** [comment]
It would be good, to mention tha5

**Comment by jakehamilton** [comment]
I've added a section to the readme :+1:

**Comment by bbigras** [comment]
Does this have anything to do with S3 Glacier?

When I read "Cold storage made easy", the first thing that comes to my mind is glacier.

**Comment by jakehamilton** [comment]
> Does this have anything to do with S3 Glacier?
> 
> When I read "Cold storage made easy", the first thing that comes to my mind is glacier.

No, this project is for managing zfs backups on external drives.
